import "primereact/resources/themes/lara-light-cyan/theme.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'primereact/resources/primereact.min.css';
import "primeflex/primeflex.css";
import "primeicons/primeicons.css";
import { PrimeReactProvider } from "primereact/api";
import { ThemeProvider } from "@/state-management/theme-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={inter.className}>
        <PrimeReactProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
